export const userDetails = {
  UPDATE_USER_DETAILS: 'UPDATE_USER_DETAILS',
  GET_USER_DETAILS: 'GET_USER_DETAILS',
  GET_USERNAME_AVAILABILITY: 'GET_USERNAME_AVAILABILITY'
} as const;

export const blogs = {
  GET_USER_BLOGS: 'GET_USER_BLOGS',
  CREATE_USER_BLOG: 'CREATE_USER_BLOG'
};

export const work = {
  CREATE_WORK: 'CREATE_WORK'
};
