export const userDetails = {
  FOLLOW_USER: 'FOLLOW_USER',
  UNFOLLOW_USER: 'UNFOLLOW_USER',
  UPDATE_USER_DETAILS: 'UPDATE_USER_DETAILS',
  GET_USER_DETAILS: 'GET_USER_DETAILS',
  GET_USERNAME_AVAILABILITY: 'GET_USERNAME_AVAILABILITY'
} as const;

export const blogs = {
  GET_USER_BLOGS: 'GET_USER_BLOGS',
  CREATE_USER_BLOG: 'CREATE_USER_BLOG'
};

export const work = {
  CREATE_WORK: 'CREATE_WORK',
  GET_USER_WORKS: 'GET_USER_WORKS'
};

export const powst = {
  GET_ALL_POWSTS: 'GET_ALL_POWSTS',
  LIKE_POWST: 'LIKE_POWST',
  UNLIKE_POWST: 'UNLIKE_POWST'
};
